[package]
name = "rust-fifo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
tokio-util = "0.7"
nix = "0.27"
futures = "0.3"
libc = "0.2.95"